Repository unitedoperations/UnitedOperationsFramework, pull requests merged in 2019-04, with the labels that each got.

#101 Fixes for several issues
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/BluforMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/CivMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/IndforMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/MissionNotesMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/OpforMenu.hpp
  uo_sys_framework/BriefingModule/cfgFunctions/common/fn_ExportBriefings.sqf
  uo_sys_framework/BriefingModule/defines/blufor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/civilian_briefing.hpp
  uo_sys_framework/BriefingModule/defines/indfor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/opfor_briefing.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportLoadoutToClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportLoadoutToProfileAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportToClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportToProfileAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportFromClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportFromProfileAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportLoadoutFromClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportLoadoutFromProfileAttribute.hpp
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ExportLoadoutSettings.sqf
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ExportSettings.sqf
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ImportLoadoutSettings.sqf
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ImportSettings.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_ImportLoadoutFromProfileAttributeAttrLoad.sqf
  uo_sys_framework/Core/cfgFunctions/EventHandlers/fn_KilledHandler.sqf
  uo_sys_framework/Core/cfgFunctions/EventHandlers/fn_RespawnHandler.sqf
  uo_sys_framework/Core/cfgFunctions/Respawn/fn_HandlePlayerRespawn.sqf
  uo_sys_framework/Core/cfgXEH/Killed/CAManBaseKilled.sqf
  uo_sys_framework/Core/cfgXEH/Respawn/CAManBaseRespawn.sqf
  uo_sys_framework/Core/display3DEN/MenuDoc.hpp
  uo_sys_framework/script_macros.hpp
  uo_sys_framework/script_mod.hpp
Labels: fixes

#97 Dev to master
  uo_sys_framework/AOLimitModule/cfgVehicles.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/BluforMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/CivMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/IndforMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/MissionNotesMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/OpforMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/cfg3denMenuCategories.hpp
  uo_sys_framework/BriefingModule/cfgFunctions/common/fn_ExportBriefings.sqf
  uo_sys_framework/BriefingModule/defines/blufor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/civilian_briefing.hpp
  uo_sys_framework/BriefingModule/defines/indfor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/opfor_briefing.hpp
  uo_sys_framework/CaptureZoneModule/cfgVehicles.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category1Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category2Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category3Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category4Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category5Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category6Menu.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportLoadoutToClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportLoadoutToProfileAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportToClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ExportToProfileAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportFromClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportFromProfileAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportLoadoutFromClipboardAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/ImportLoadoutFromProfileAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/SizeAttribute.hpp
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ExportLoadoutSettings.sqf
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ExportSettings.sqf
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ImportLoadoutSettings.sqf
  uo_sys_framework/Core/cfgFunctions/3DENExportImport/fn_ImportSettings.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_ImportLoadoutFromProfileAttributeAttrLoad.sqf
  uo_sys_framework/Core/cfgFunctions/EventHandlers/fn_KilledHandler.sqf
  uo_sys_framework/Core/cfgFunctions/EventHandlers/fn_RespawnHandler.sqf
  uo_sys_framework/Core/cfgFunctions/Respawn/fn_HandlePlayerRespawn.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_alivePlayers.sqf
  uo_sys_framework/Core/cfgXEH/Killed/CAManBaseKilled.sqf
  uo_sys_framework/Core/cfgXEH/Respawn/CAManBaseRespawn.sqf
  uo_sys_framework/Core/display3DEN/MenuDoc.hpp
  uo_sys_framework/CoverMapModule/cfgVehicles.hpp
  uo_sys_framework/GearModule/cfg3den/cfg3denMenuCategories.hpp
  uo_sys_framework/GearModule/cfgFunctions/3den/fn_GearLoadPreset.sqf
  uo_sys_framework/GearModule/cfgFunctions/3den/fn_GearTypeLoad3DEN.sqf
  uo_sys_framework/GearModule/cfgFunctions/Attributes/fn_ACEGearClassAttribute_AttrLoad.sqf
  uo_sys_framework/GearModule/cfgFunctions/Attributes/fn_ACEGearClassAttribute_AttrReLoad.sqf
  uo_sys_framework/HeadlessAIModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/HostageModule/cfgFunctions/common/fn_Set.sqf
  uo_sys_framework/HostageModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/SetupTimerModule/cfgVehicles.hpp
  uo_sys_framework/StartInParachuteModule/cfg3den/Modules/StartInParachute.hpp
  uo_sys_framework/StartInParachuteModule/cfgFunctions/common/fn_DoParachute.sqf
  uo_sys_framework/StartInParachuteModule/cfgFunctions/init/fn_initPost.sqf
  uo_sys_framework/StartInParachuteModule/cfgXEH/PreInit.hpp
  uo_sys_framework/StartInParachuteModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/StartInParachuteModule/cfgXEH/init/PreInit.sqf
  uo_sys_framework/config.cpp
  uo_sys_framework/script_macros.hpp
  uo_sys_framework/script_mod.hpp
Labels: addition, fixes

#102 Respawn Settings/Listbox Checkboxes
  uo_sys_framework/Core/cfg3den/Respawn/BluforRespawn.hpp
  uo_sys_framework/Core/cfg3den/Respawn/CivilianRespawn.hpp
  uo_sys_framework/Core/cfg3den/Respawn/IndforRespawn.hpp
  uo_sys_framework/Core/cfg3den/Respawn/OpforRespawn.hpp
  uo_sys_framework/Core/cfgAttributes/Respawn/RespawnTypeAttribute.hpp
  uo_sys_framework/Core/cfgFunctions.hpp
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_AttrLoad.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_AttrSave.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_onLBSelChanged.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_onLoad.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnTemplates_onLBSelChanged.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnTemplates_onSetFocus.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_respawntemplates_attr_load.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_respawntemplates_attr_save.sqf
  uo_sys_framework/Core/cfgFunctions/Respawn/fn_HandlePlayerRespawn.sqf
  uo_sys_framework/Core/cfgFunctions/Spectator/fn_spectate.sqf
  uo_sys_framework/Core/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/Core/cfgXEH/init/ServerPreInit.sqf
Labels: fix

#108 Fix to race condition in spectator
  CHANGELOG.md
  uo_sys_framework/Core/cfg3den/EndConditions/Category1Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category2Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category3Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category4Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category5Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category6Menu.hpp
  uo_sys_framework/Core/cfg3den/Mission/VisionSettings.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category1Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category2Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category3Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category4Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category5Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category6Loop.hpp
  uo_sys_framework/Core/cfgFunctions/Spectator/fn_spectate.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_eventRespawned.sqf
  uo_sys_framework/Core/cfgXEH/Killed/CAManBaseKilled.sqf
  uo_sys_framework/Core/cfgXEH/Respawn/CAManBaseRespawn.sqf
Labels: fix, needs testing

#113 Fixes to Endscreen, Add Unit Acre Babel, Fix to Extract condition
  CHANGELOG.md
  uo_sys_framework/ACREModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/ACREModule/cfgAttributes.hpp
  uo_sys_framework/ACREModule/cfgAttributes/AdditionalLanguageAttribute.hpp
  uo_sys_framework/ACREModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/Core/cfg3den/EndConditions/Category1Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category2Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category3Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category4Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category5Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category6Menu.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category1Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category2Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category3Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category4Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category5Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category6Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/fn_hasExtracted.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_getDamagedAssets.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_stackNames.sqf
  uo_sys_framework/Core/cfgXEH/Killed/CAManBaseKilled.sqf
  uo_sys_framework/Core/cfgXEH/Respawn/CAManBaseRespawn.sqf
  uo_sys_framework/Core/cfgXEH/init/ServerPostInit.sqf
  uo_sys_framework/ShotCountModule/cfgXEH/init/ClientPreInit.sqf
Labels: fixes

#115 Fix Acre Channelname , Fix ACRE Ear Channel, Fix ACRE Channel
  CHANGELOG.md
  uo_sys_framework/ACREModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/ACREModule/cfgXEH/init/ClientPreInit.sqf
Labels: being worked on, fixes

#116 Dev to master
  .gitignore
  CHANGELOG.md
  uo_sys_framework/ACREModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/ACREModule/cfgAttributes.hpp
  uo_sys_framework/ACREModule/cfgAttributes/AdditionalLanguageAttribute.hpp
  uo_sys_framework/ACREModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/BriefingModule/defines/blufor_briefing.hpp
  uo_sys_framework/CaptureZoneModule/cfgFunctions/common/fn_Loop.sqf
  uo_sys_framework/Core/CfgUO/RespawnTemplates.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category1Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category2Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category3Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category4Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category5Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category6Menu.hpp
  uo_sys_framework/Core/cfg3den/Mission/VisionSettings.hpp
  uo_sys_framework/Core/cfg3den/Respawn/BluforRespawn.hpp
  uo_sys_framework/Core/cfg3den/Respawn/CivilianRespawn.hpp
  uo_sys_framework/Core/cfg3den/Respawn/IndforRespawn.hpp
  uo_sys_framework/Core/cfg3den/Respawn/OpforRespawn.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/SliderAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/Main/MissionTypeAttribute.hpp
  uo_sys_framework/Core/cfgAttributes/Respawn/RespawnTypeAttribute.hpp
  uo_sys_framework/Core/cfgFunctions.hpp
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_AttrLoad.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_AttrSave.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_onLBSelChanged.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnCombo_onLoad.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnTemplates_onLBSelChanged.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_RespawnTemplates_onSetFocus.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_respawntemplates_attr_load.sqf
  uo_sys_framework/Core/cfgFunctions/Attributes/fn_respawntemplates_attr_save.sqf
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category1Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category2Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category3Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category4Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category5Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/defines/Category6Loop.hpp
  uo_sys_framework/Core/cfgFunctions/EndConditions/fn_hasExtracted.sqf
  uo_sys_framework/Core/cfgFunctions/Respawn/fn_HandlePlayerRespawn.sqf
  uo_sys_framework/Core/cfgFunctions/Spectator/fn_spectate.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_eventRespawned.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_getDamagedAssets.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_stackNames.sqf
  uo_sys_framework/Core/cfgXEH/Respawn/CAManBaseRespawn.sqf
  uo_sys_framework/Core/cfgXEH/init/ClientPostInit.sqf
  uo_sys_framework/Core/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/Core/cfgXEH/init/ServerPostInit.sqf
  uo_sys_framework/Core/cfgXEH/init/ServerPreInit.sqf
  uo_sys_framework/GearModule/cfgFunctions/3den/fn_GearTypeLoad3DEN.sqf
  uo_sys_framework/GearModule/cfgFunctions/Olsen/fn_OlsenGearScript.sqf
  uo_sys_framework/GearModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/GearModule/cfgXEH/init/PreInit.sqf
  uo_sys_framework/ShotCountModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/config.cpp
  uo_sys_framework/script_mod.hpp
Labels: additions, fixes
