Repository unitedoperations/UnitedOperationsFramework, pull requests merged in 2019-03, with the labels that each got.

#62 ACRE Module as Example Page
  _config.yml
  _includes/foot.html
  _layouts/default.html
  _sass/custom/custom.scss
  docs/toc/acre.md
  docs/toc/modules.md
  index.md
Labels: documentation

#65 Bugfixes
  uo_sys_framework/ACREModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_spawnAI.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_spawnVehicle.sqf
  uo_sys_framework/HeadlessAIModule/cfgFunctions/create/fn_createUnit.sqf
  uo_sys_framework/HostageModule/cfgFunctions/common/fn_HostageSet.sqf
  uo_sys_framework/HostageModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/config.cpp
Labels: Fix, needs testing

#71 Fix to issues caused by github desktop merge
  uo_sys_framework/Core/cfgFunctions/3DENInits/fn_setDefaults.sqf
  uo_sys_framework/Core/cfgXEH/init/GlobalPreInit.sqf
  uo_sys_framework/HostageModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/HostageModule/cfgFunctions/common/fn_delayedAttribute.sqf
Labels: Fix

#74 Olsen Gear Page fully complete.
  docs/mission-makers/olsen-gear.md
  resources/images/olsen/gear_configure.png
  resources/images/olsen/gear_editor_demo.gif
  resources/images/olsen/gear_enable.png
  resources/images/olsen/gear_roles.png
Labels: documentation

#79 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: clarification

#84 Fixes for PR #81
  .gitignore
  uo_sys_framework/HostageModule/cfgFunctions/common/fn_Rescue.sqf
  uo_sys_framework/HostageModule/cfgFunctions/common/fn_Set.sqf
Labels: Fixes

#85 Update README.md for version 1.0.4
  README.md
Labels: enhancement

#86 Woops
  README.md
Labels: Fix

#87 Fix to freeze vehicles and fix for AssetTracking
  uo_sys_framework/AutoTrackAssetModule/cfgFunctions/common/fn_Init.sqf
  uo_sys_framework/Core/cfgFunctions/EndScreen/fn_endscreen.sqf
Labels: Fixes

#92 Fix invisible configure mission notes
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/MissionNotesMenu.hpp
  uo_sys_framework/BriefingModule/cfg3DEN/cfg3denMenuCategories.hpp
Labels: Fix

#93 Fixes for 1.0.4
  uo_sys_framework/AOLimitModule/cfgVehicles.hpp
  uo_sys_framework/CaptureZoneModule/cfgVehicles.hpp
  uo_sys_framework/Core/cfgAttributes/3DEN/SizeAttribute.hpp
  uo_sys_framework/Core/display3DEN/MenuDoc.hpp
  uo_sys_framework/CoverMapModule/cfgVehicles.hpp
  uo_sys_framework/GearModule/cfg3den/cfg3denMenuCategories.hpp
  uo_sys_framework/GearModule/cfgFunctions/3den/fn_GearLoadPreset.sqf
  uo_sys_framework/GearModule/cfgFunctions/3den/fn_GearTypeLoad3DEN.sqf
  uo_sys_framework/GearModule/cfgFunctions/Attributes/fn_ACEGearClassAttribute_AttrLoad.sqf
  uo_sys_framework/GearModule/cfgFunctions/Attributes/fn_ACEGearClassAttribute_AttrReLoad.sqf
  uo_sys_framework/HeadlessAIModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/SetupTimerModule/cfgVehicles.hpp
  uo_sys_framework/config.cpp
  uo_sys_framework/script_mod.hpp
Labels: Fixes

#94 WIP: Hostage interaction moved to hands, tooltip clarification for require extraction E.C.
  uo_sys_framework/BriefingModule/cfg3DEN/Briefing/MissionNotesMenu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category1Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category2Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category3Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category4Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category5Menu.hpp
  uo_sys_framework/Core/cfg3den/EndConditions/Category6Menu.hpp
  uo_sys_framework/Core/cfgFunctions/common/fn_alivePlayers.sqf
  uo_sys_framework/HostageModule/cfgFunctions/common/fn_Set.sqf
  uo_sys_framework/HostageModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/StartInParachuteModule/cfg3den/Modules/StartInParachute.hpp
  uo_sys_framework/StartInParachuteModule/cfgFunctions/common/fn_DoParachute.sqf
  uo_sys_framework/StartInParachuteModule/cfgFunctions/init/fn_initPost.sqf
  uo_sys_framework/StartInParachuteModule/cfgXEH/PreInit.hpp
  uo_sys_framework/StartInParachuteModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/StartInParachuteModule/cfgXEH/init/PreInit.sqf
  uo_sys_framework/config.cpp
Labels: additions, enhancement, fixes
