Repository unitedoperations/UnitedOperationsFramework, pull requests merged in 2019-05, with the labels that each got.

#121 Fixes to Briefing export and Briefing
  uo_sys_framework/BriefingModule/cfgFunctions/common/fn_ExportBriefings.sqf
  uo_sys_framework/BriefingModule/defines/blufor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/civilian_briefing.hpp
  uo_sys_framework/BriefingModule/defines/indfor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/opfor_briefing.hpp
Labels: fixes

#124 Fix duplicate briefing, Add ACRE Preset for Vehicle
  uo_sys_framework/ACREModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/ACREModule/cfgAttributes.hpp
  uo_sys_framework/ACREModule/cfgAttributes/VehicleRadioPresetAttribute.hpp
  uo_sys_framework/ACREModule/cfgXEH/PreInit.hpp
  uo_sys_framework/ACREModule/cfgXEH/init/ServerPreInit.sqf
  uo_sys_framework/AIDriversModule/cfgFunctions/EH/fn_InitPost.sqf
  uo_sys_framework/AIDriversModule/cfgFunctions/common/fn_EnableAIDriver.sqf
  uo_sys_framework/AIDriversModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/AOLimitModule/cfgFunctions/common/fn_Init.sqf
  uo_sys_framework/BriefingModule/cfgFunctions/common/fn_ExportBriefings.sqf
  uo_sys_framework/BriefingModule/defines/blufor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/civilian_briefing.hpp
  uo_sys_framework/BriefingModule/defines/indfor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/opfor_briefing.hpp
  uo_sys_framework/Core/cfgFunctions/EndScreen/fn_endscreen.sqf
  uo_sys_framework/Core/cfgFunctions/JiP/fn_GiveActions.sqf
  uo_sys_framework/Core/cfgFunctions/JiP/fn_Teleport.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_endMission.sqf
  uo_sys_framework/Core/cfgXEH/init/ClientPostInit.sqf
  uo_sys_framework/Core/cfgXEH/init/GlobalPreInit.sqf
  uo_sys_framework/Core/cfgXEH/initPost/CAManBaseInitPost.sqf
  uo_sys_framework/GearModule/cfgFunctions/Olsen/fn_OlsenGearScript.sqf
  uo_sys_framework/GearModule/cfgFunctions/Olsen/fn_addItemRandomOrg.sqf
  uo_sys_framework/MapAndCompassRemoverModule/cfgFunctions/init/fn_initPost.sqf
  uo_sys_framework/ShotCountModule/cfgFunctions/common/fn_addEH.sqf
  uo_sys_framework/StartInParachuteModule/cfgFunctions/init/fn_initPost.sqf
  uo_sys_framework/script_mod.hpp
Labels: pull request/fixes

#131 Fix for wrong ACRE channels being set
  uo_sys_framework/ACREModule/cfgXEH/init/ClientPreInit.sqf
Labels: pull request/fix, pull request/needs testing

#128 1.0.6 Warmfix
  uo_sys_framework/ACREModule/cfgAttributeCategories/Object.hpp
  uo_sys_framework/ACREModule/cfgAttributes.hpp
  uo_sys_framework/ACREModule/cfgAttributes/VehicleRadioPresetAttribute.hpp
  uo_sys_framework/ACREModule/cfgXEH/PreInit.hpp
  uo_sys_framework/ACREModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/ACREModule/cfgXEH/init/ServerPreInit.sqf
  uo_sys_framework/AIDriversModule/cfgFunctions/EH/fn_InitPost.sqf
  uo_sys_framework/AIDriversModule/cfgFunctions/common/fn_EnableAIDriver.sqf
  uo_sys_framework/AIDriversModule/cfgXEH/init/ClientPreInit.sqf
  uo_sys_framework/AOLimitModule/cfgFunctions/common/fn_Init.sqf
  uo_sys_framework/BriefingModule/cfgFunctions/common/fn_ExportBriefings.sqf
  uo_sys_framework/BriefingModule/defines/blufor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/civilian_briefing.hpp
  uo_sys_framework/BriefingModule/defines/indfor_briefing.hpp
  uo_sys_framework/BriefingModule/defines/opfor_briefing.hpp
  uo_sys_framework/Core/cfgFunctions/EndScreen/fn_endscreen.sqf
  uo_sys_framework/Core/cfgFunctions/JiP/fn_GiveActions.sqf
  uo_sys_framework/Core/cfgFunctions/JiP/fn_Teleport.sqf
  uo_sys_framework/Core/cfgFunctions/common/fn_endMission.sqf
  uo_sys_framework/Core/cfgXEH/init/ClientPostInit.sqf
  uo_sys_framework/Core/cfgXEH/init/GlobalPreInit.sqf
  uo_sys_framework/Core/cfgXEH/initPost/CAManBaseInitPost.sqf
  uo_sys_framework/GearModule/cfgFunctions/Olsen/fn_OlsenGearScript.sqf
  uo_sys_framework/GearModule/cfgFunctions/Olsen/fn_addItemRandomOrg.sqf
  uo_sys_framework/MapAndCompassRemoverModule/cfgFunctions/init/fn_initPost.sqf
  uo_sys_framework/ShotCountModule/cfgFunctions/common/fn_addEH.sqf
  uo_sys_framework/StartInParachuteModule/cfgFunctions/init/fn_initPost.sqf
  uo_sys_framework/script_mod.hpp
Labels: general/additions, general/enhancement, pull request/fixes

#133 Update Bug Report Template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: general/enhancement

#134 Fix to Killcam not appearing
  uo_sys_framework/Core/cfgFunctions.hpp
  uo_sys_framework/Core/cfgFunctions/EventHandlers/fn_KilledHandler.sqf
  uo_sys_framework/Core/cfgFunctions/Spectator/fn_KillCamToggleKeyH.sqf
  uo_sys_framework/Core/cfgFunctions/Spectator/fn_spectate.sqf
  uo_sys_framework/Core/cfgXEH/Killed/CAManBaseKilled.sqf
Labels: pull request/fix

#136 Addition of Context Menu Navigation Options
  uo_sys_framework/ACREModule/display3DEN/ContextMenu.hpp
  uo_sys_framework/ACREModule/display3DEN/Menu.hpp
  uo_sys_framework/BriefingModule/display3DEN/ContextMenu.hpp
  uo_sys_framework/BriefingModule/display3DEN/Menu.hpp
  uo_sys_framework/Core/MainExternal.hpp
  uo_sys_framework/Core/display3DEN/ContextMenu.hpp
  uo_sys_framework/Core/display3DEN/Menu3DEN.hpp
  uo_sys_framework/Core/display3DEN/MenuDoc.hpp
  uo_sys_framework/Core/display3DEN/MenuRespawn.hpp
  uo_sys_framework/GearModule/display3DEN/ContextMenu.hpp
  uo_sys_framework/GearModule/display3DEN/Menu.hpp
  uo_sys_framework/config.cpp
Labels: general/enhancement

#141 WIP: Update experimental to latest master + Respawn Zone changes and HC Slot Enforcement
  .github/ISSUE_TEMPLATE/bug_report.md
  CHANGELOG.md
  README.md
  uo_sys_framework/Core/cfg3den/Mission/MainMenu.hpp
  uo_sys_framework/Core/cfg3denEH.hpp
  uo_sys_framework/Core/cfgFunctions.hpp
  uo_sys_framework/Core/cfgFunctions/3DENEditor/fn_checkHeadless.sqf
  uo_sys_framework/Core/cfgFunctions/3DENEditor/fn_checkPlayable.sqf
  uo_sys_framework/Core/cfgFunctions/3DENEventHandlers/fn_displayHCSlotRequired.sqf
  uo_sys_framework/Core/cfgFunctions/Respawn/fn_HandlePlayerRespawn.sqf
  uo_sys_framework/Core/cfgFunctions/Respawn/fn_SetRespawnModule.sqf
  uo_sys_framework/Core/cfgVehicles.hpp
  uo_sys_framework/script_mod.hpp
Labels: pull request/exploring
